### ISSUE TITLE
parameters bug

### ISSUE THREAD

**Issue by glejeune** [glejeune/ruby-xslt#1]
In my recent use of it, I have run across what seems to be a bug
involving memory corruption.  I first saw this in a moderately complex
program which would crash due to an internal error some time after
exhibiting the corruption, but I was able to boil this down into a
surprisingly short test program which exhibits the corruption
(although not the subsequent crash which I assume is associated with
it, as this requires running for longer).  Here it is:

```
#!/usr/bin/ruby

require 'rubygems'
require 'xml/smart'
require 'xml/xslt'

XsltDoc = %{\
  <?xml version="1.0" encoding="UTF-8"?>
  <xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="xml"/>
    <xsl:template match="text()"/>
    <xsl:template match="/">
      <record>
        <opacVendor><xsl:value-of select="$vendor"/></opacVendor>
      </record>
    </xsl:template>
  </xsl:stylesheet>
}

XmlDoc = %{\
  <?xml version="1.0" encoding="UTF-8"?>
  <emptyDocument/>
}

Vendor = "Some Specific Vendor"

def zoom2torus()
  xslt = XML::XSLT.new()
  xslt.xsl = XML::Smart.string(XsltDoc)
  xslt.xml = XML::Smart.string(XmlDoc)

  puts "before xslt.parameters assignment, Vendor=[#{Vendor}]"
  xslt.parameters = { "vendor" => Vendor }
  puts "after  xslt.parameters assignment, Vendor=[#{Vendor}]"

  xslt.serve
end

dummy1 = zoom2torus()
dummy2 = zoom2torus()
```

I am using version 0.96 of Ruby-XSLT, installed from the gem, on
Ubuntu GNU/Linux 9.10 (Karmic Koala) which provides ruby 1.8.7
(2009-06-12 patchlevel 174).  Running the program yields:

```
$ ruby xslt-bug.rb
before xslt.parameters assignment, Vendor=[Some Specific Vendor]
after  xslt.parameters assignment, Vendor=[Some Specific Vendor']
before xslt.parameters assignment, Vendor=[Some Specific Vendor']
after  xslt.parameters assignment, Vendor=[Some Specific Vendor']
Invalid expression
runtime error
Evaluating user parameter vendor failed
```

You will note that the value of the global variable Vendor is
corrupted by the act of being passed into xslt.parameters=, and that
reassigning it the second time when using the corrupted value results
in an error (though not the same one I got in my longer-running
program).  Similar corruption occurs if the value passed into the
parameters= call is an instance variable.

**Comment by bkline** [comment]
I'm a little puzzled by the statuses that appear to be assigned to this bug report, as it's marked both "In Progress" and "Closed" at the same time. How can that be, please? And if it's closed, what was the resolution?
